const languageOptions = [
    { value: "en", text: "English (en)" },
    { value: "fr", text: "French (fr)" },
    { value: "es", text: "Spanish (es)" },
    { value: "de", text: "German (de)" },
    { value: "it", text: "Italian (it)" },
    { value: "pt", text: "Portuguese (pt)" },
    { value: "ru", text: "Russian (ru)" },
    { value: "ja", text: "Japanese (ja)" },
    { value: "ko", text: "Korean (ko)" },
    { value: "zh-cn", text: "Chinese (zh)" },
    { value: "ar", text: "Arabic (ar)" },
    { value: "tr", text: "Turkish (tr)" },
    { value: "pl", text: "Polish (pl)" },
    { value: "nl", text: "Dutch (nl)" },
    { value: "sv", text: "Swedish (sv)" },
    { value: "da", text: "Danish (da)" },
    { value: "fi", text: "Finnish (fi)" },
    { value: "no", text: "Norwegian (no)" },
    { value: "cs", text: "Czech (cs)" },
    { value: "hu", text: "Hungarian (hu)" },
    { value: "el", text: "Greek (el)" },
    { value: "th", text: "Thai (th)" },
    { value: "id", text: "Indonesian (id)" },
    { value: "vi", text: "Vietnamese (vi)" },
    { value: "hi", text: "Hindi (hi)" },
    { value: "bn", text: "Bengali (bn)" },
    { value: "fa", text: "Persian (fa)" },
    { value: "he", text: "Hebrew (he)" },
    { value: "ur", text: "Urdu (ur)" },
    { value: "tl", text: "Filipino (tl)" },
    { value: "ms", text: "Malay (ms)" },
    { value: "ta", text: "Tamil (ta)" },
    { value: "kn", text: "Kannada (kn)" },
    { value: "ml", text: "Malayalam (ml)" },
    { value: "mr", text: "Marathi (mr)" },
    { value: "te", text: "Telugu (te)" },
    { value: "ne", text: "Nepali (ne)" },
    { value: "si", text: "Sinhalese (si)" },
    { value: "my", text: "Burmese (my)" },
    { value: "km", text: "Khmer (km)" },
    { value: "lo", text: "Lao (lo)" }
];



module.exports =  languageOptions